print ("My Name Is Cyrus")
print ("Robot")
print ("Rude")
print ("I'm")
print ("Artist")
print ("Redo")
print ("A random sentence")
print ("Ameteur")
print ("My Favourite Color is Blue")
print ("A B C D E F G H I ...")