print ("My Name Is Cyrus")
print ("Robot")
print ("Rude")
print ("I'm")
print ("Artist")
print ("Redo")
print ("A random sentence")
print ("Ameteur")
print ("My Favourite Color is Blue")
print ("A B C D E F G H I ...")
print ("Acne")
print ("Rodeo")
print ("Add")
print ("Lips")
print ("Any")
print ("Agate")
print ("I exist")
print ("Attorney")
print ("Remix")
print ("Mars")
print ("Acheron")
print ("Oh, So Random Words?")
print ("Remaking")
print ("Error. Read the second letter of every print.")